### ISSUE TITLE
Status 404 für bestehende Anträge

### ISSUE THREAD

**Issue by tiwillms** [hypoport/antraege-auslesen-api#12]
https://baufismart.api.europace.de/v2/antraege/YL3706/1/1 gibt für Plakette YAV26 einen 404 zurück. Recht müsste aber vorhanden sein.

**Comment by caspii** [comment]
Von MediaWorx

**Comment by gruenewa** [comment]
Die Plakette hat kein Übernahmerecht auf den Kreditbearbeiter und darf folglich auch nicht auf den Antrag zugreifen.
