### ISSUE TITLE
Tilgungsbeginn wurde nicht erfasst - wo erfasse ich den denn?

### ISSUE THREAD

**Issue by u00kram** [hypoport/antraege-auslesen-api#15]
Hallo Herr Wrede, 
neuer Testfall QS6759 - Vorhaben ASF / Finanzierungswunsch Annuitätendarlehen oder auch Forwarddarlehen -> Nicht annehmbar, weil "der Tilgungsbeginn für das Annuitätendarlehen über 50.000 Euro nicht erfasst wurde".
Das ist neu und wo erfasse ich denn diesen Tilgungsbeginn?

**Comment by u00kram** [comment]
Ich bin fündig geworden. 
Dieser Tilgungsbeginn wurde bisher nicht abgefragt und ich musst suchen wo sich die Eingabe verbirgt.
Eine lfd. Info über Änderungen wäre ziemlich hilfreich ... wie schon geschrieben.

**Comment by caspii** [comment]
Sie können sich hier zum Product Newsletter eintragen, darüber werden sie auch über Änderungen informiert https://europace2.us2.list-manage.com/subscribe?u=92faf39d7173cf6cddfa41555&id=e7692e938c

Ich schließe jetzt dieses Ticket
