### ISSUE TITLE
Verrechnung mit dem Finanzierungsüberschuss und der Differenz zwischen aktuellem Wert und max. aufzulösendem Wert stimmt nicht.

### ISSUE THREAD

**Issue by ollio** [hypoport/antraege-auslesen-api#8]
wir importieren die Daten über die Anträge Auslesen API in unsere Systeme. Dabei ist uns folgendes aufgefallen:
Die bei den Antragstellern erfassten Vermögen haben einen aktuellen Wert. Zusätzlich kann man angeben, wie viel davon maximal aufzulösen und für die Finanzierung einzusetzen ist. Daraus ergibt sich ggf. ein Finanzierungsüberschuss. Bei der Bereitstellung der Daten in der API werden allerdings nicht die originalen Eingaben übergeben, sondern eine seltsame Verrechnung mit dem Finanzierungsüberschuss und der Differenz zwischen aktuellem Wert und max. aufzulösendem Wert.
Beispiel:
Bank-/Sparguthaben
Angabe in GUI: aktueller Wert = 165.000 EUR; max. aufzulösender Wert = 164.650 EUR; daraus resultierender Finanzierungsüberschuss = 22.875 EUR
Übergabe in API: aktueller Wert = 164.650 EUR; max. aufzulösender Wert = 141.775 EUR

Auch wenn ich das für den aufzulösenden Wert noch einigermaßen nachvollziehen könnte (Finanzierungsüberschuss auf 0 bringen --> dennoch halte ich die Übergabe des original angegebenen Wertes für besser), ist die Angabe des aktuellen Wertes definitiv nicht korrekt.

**Comment by ollio** [comment]
Der Vorgang im Testmodus ist LF2019

**Comment by ollio** [comment]
Ich habe nun versucht das Problem zu verstehen, leider kann ich es nicht nachvollziehen.
An dem Vorgang LF2019 hängen 28 Teilanträge. In welchem ist denn der Fehler aufgetreten?

Wenn ein Antrag erstellt wurde, dann werden die erfassten Daten zum Zeitpunkt der Annahme an den Antrag kopiert. Wenn Sie dann im Nachgang die Erfassten Daten anpassen, wird sich diese Änderung nicht mehr auf die erfassten Daten des Antrags auswirken.

**Comment by caspii** [comment]
Das ist das gleiche Thema wie hier: #18. Ich schliesse dieses Ticket da duplicate.

Es ist soweit ich das sehen kann kein Bug, sondern nur eine Inkonsistenz zwischen Frontend und API
